services:
  db:
    image: postgres:latest
    expose:
      - 5432
    environment: # change these values for production
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurant
    volumes:
      - ./.db-data/:/var/lib/postgresql/data # mount local folder for data persistance
  api:
    build:
      context: ./api
    expose:
      - 3000
    depends_on:
      - db
      - redis
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  redis:
    image: redis
    volumes:
      - ./.cache:/var/lib/redis
    expose:
      - 6379